# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='page_views',
            field=models.IntegerField(default=0),
        ),
    ]
