# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_page_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='subtag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
