# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180211_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtag',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
